### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by FelixZhang7** [jxbz/nero#1]
line 58, in step
    state['exp_avg_sq'] = self.beta * state['exp_avg_sq'] + (1-self.beta) * neuron_norm(p.grad)**2

**Comment by jxbz** [comment]
Hey @FelixZhang7, could you check that you moved the neural net to GPU before you create the optimiser? Like this:

```python
net = net.cuda()
optimizer = Nero(net.parameters(), lr=0.01)
```

The optimiser init function assumes all tensors are already on the device they will be trained on. If this doesn't work, let me know.
