### ISSUE TITLE
batch.sh file missing for wikitext2

### ISSUE THREAD

**Issue by MathieuTuli** [jxbz/nero#2]
Hi! Thanks the nice and clean repo, really refreshing to work with. I noticed in the [wikitext2 section](https://github.com/jxbz/nero/tree/master/wikitext2) experiments that there's a `batch.sh` file mentioned for the commands used in the paper, but I can't seem to find it anywhere?  Further, I noticed in the paper mention of lr scheduling using step size 10 epoch and gamma 0.1 for the wikitext2 experiments but do not see any implementation of a scheduler in the code. Is this an oversight?

**Comment by jxbz** [comment]
Hi @MathieuTuli, thanks a lot for pointing this out.

- `batch.sh` was renamed to `figure7.sh`
- the lr decay happens in the conditional block at line 292 of `main.py`.

Let me know if you have more questions!
